name: Update version file on release
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    outputs:
      status: ${{ steps.early.conclusion }}
      
    steps:
      - id: early
        name: Null tag check
        if: github.event.release.tag_name != null
        run: echo "Release version ${{ github.event.release.tag_name }}"
        
  update:
    runs-on: ubuntu-latest
    
    needs: check
    if: needs.check.outputs.status == 'success'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update version file
        run: echo ${{ github.event.release.tag_name }} > version.txt

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'GitHub-Actions-Bot@users.noreply.github.com'
          git add version.txt
          git commit -m "Updated version file"
          git push origin HEAD:master
